## This laboratory will be conducted over two sessions
## You are expected to finish the software and test the code in simulation between the sessions! ##

# Manipulating objects

For this laboratory, we will use two robots distant from each other of 25cm as depicted in the figure below

<img src="./2_robot_config.png" width="500">

There is 1cm between the end-effector "shell" and the position of the frame as depicted in the figure below

<img src="./foot_close.png" width="300">

<img src="./box.jpg" width="200">

The objects to grasp are soft cubes with a 5cm side.
Three cubes are stacked on top of each other. The goal of the laboratory is to design a controller to will move the two cubes on the top away
and pick the bottom cube and lift it up by 10cm.

In [1]:
#setup nice plotting (use widget instead of notebook in the command below if you use jupyter lab)
%matplotlib widget

# we import useful libraries
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt

# this function returns the body Jacobian
from robot_utils import getBodyJacobianOrientedLikeSpatialFrame
from scipy import optimize

# we import the robot class
use_real_robot = False

if use_real_robot:
    from nyu_finger import NYUFingerReal    
else:
    from nyu_finger_simulator import NYUFingerSimulator


# here we define the global variables for the robot size
l0 = 0.3
l1 = 0.16
l2 = 0.16
l3 = 0.014

pybullet build time: Dec  1 2021 18:33:43


In [2]:
def translate(vector):
    transform = np.eye(4)
    transform[:3, 3] = vector
    return transform

def rotateX(angle):
    transform = np.eye(4)
    sin = np.sin(angle)
    cos = np.cos(angle)
    transform[1, 1] = cos
    transform[1, 2] = -sin
    transform[2, 1] = sin
    transform[2, 2] = cos
    return transform

def rotateY(angle):
    transform = np.eye(4)
    sin = np.sin(angle)
    cos = np.cos(angle)
    transform[0, 0] = cos
    transform[0, 2] = sin
    transform[2, 0] = -sin
    transform[2, 2] = cos
    return transform

def rotateZ(angle):
    transform = np.eye(4)
    sin = np.sin(angle)
    cos = np.cos(angle)
    transform[0, 0] = cos
    transform[0, 1] = -sin
    transform[1, 0] = sin
    transform[1, 1] = cos
    return transform


def forward_kinematics(theta):
    # assume theta is a vector, theta[0] = theta0, theta[1] = theta1, etc.
    # we define the lengths of the robot
    l0 = 0.3
    l1 = 0.16
    l2 = 0.16
    l3 = 0.014
    
    ###WRITE YOUR CODE HERE
    T = np.eye(4)
    
    TSH1 = translate(np.array([l0, 0, 0])) @ rotateX(theta[0]) 
    
    TSH2 = TSH1 @ translate(np.array([0, 0, l3])) @ rotateZ(theta[1]) 

    TSK = TSH2 @ translate(np.array([0, -l1, 0])) @ rotateZ(theta[2])
    
    TSF = TSK @ translate(np.array([0, -l2, 0]))
    
    ### we return the object
    return TSF

In [3]:
def linear_interpolate_trajectory(position_init, position_goal, t_init, t_goal, t):
    s = (t - t_init)/(t_goal - t_init)
    desired_position = position_init + s * (position_goal - position_init)
    desired_velocity = 1/(t_goal - t_init) * (position_goal - position_init)
    
    # we return the answer
    return desired_position, desired_velocity

def second_order_trajectory(position_init, position_goal, t_init, t_goal, t):
    T = t_goal - t_init
    s = 3/(T**2)*((t-t_init)**2) - 2/ (T**3)*(t-t_init)**3
    desired_position = position_init + s * (position_goal - position_init)
    desired_velocity = (6/(T**2)*(t-t_init) - 6/(T**3)*(t-t_init)**2) * (position_goal - position_init)
    
    # we return the answer
    return desired_position, desired_velocity

def third_order_trajectory(position_init, position_goal, t_init, t_goal, t):
    T = t_goal - t_init
    desired_position = position_init + (10/(T**3)*(t-t_init)**3 + -15/(T**4)*(t-t_init)**4 + \
                                        6/(T**5)*(t-t_init)**5)*(position_goal-position_init)
    desired_velocity = (30/(T**3)*(t-t_init)**2+-60/(T**4)*(t-t_init)**3+30/(T**5)*(t-t_init)**4)*(position_goal-position_init)
    
    # we return the answer
    return desired_position, desired_velocity

In [4]:
def fingertip_position_error(joint_angles, desired_fingertip_position):
    """
    fingertip_position_error function
    input joint_angles (as a 3D vector) and desired_fingertip_position (as a 3D vector)
    output the squared distance between the desired fingertip position and the one realized by joint_angles
    """
    p_fk = forward_kinematics(joint_angles)
    error = np.subtract(p_fk[:3, 3], desired_fingertip_position)
    return error.dot(error)


def inverse_geometry(desired_fingertip_position):
    """
    inverse geometry function
    input desired_fingertip_position (3D vector of desired position of the fingertip)
    output a vector of joint angles
    """
    res = optimize.minimize(fingertip_position_error, np.array([0.0, 0.0, 0.0]), args = (desired_fingertip_position))
    return res.x

## Questions
In this laboratory you are expected to re-use code from the previous laboratories (e.g. to plot, compute forward kinematics, etc).

1. Using an impedance controller (Lab4 - use the ``getBodyJacobianOrientedLikeSpatialFrame`` function to get the Jacobian) and one trajectory generation method seen in Lab3 write a complete controller that solves the problem: move the top two cubes away, grasp the last cube and move it up by 10cm.

2. Test your controller in simulation. Save and plot the results.
   
3. Test the controller on the real robots. Save and plot the results.

4. In the report, describe in details the controller you designed (what it does, etc) and the results you obtained.

5. (optional - bonus) Extend the controller to rearrange the cubes - putting the bottom one on top of the two others.

In [5]:
pos_1 = [0.44, -.16, 0]

In [ ]:
# we create a robot simulation or a real robot
if use_real_robot:
    robot1 = NYUFingerReal()
    motor_number = np.array([1,2,3])
    robot1.initialize('enp5s0f1', motor_number)
    
    robot2 = NYUFingerReal()
    motor_number = np.array([1,2,3])
    robot2.initialize('eno1', motor_number)

else:
    robot1 = NYUFingerSimulator(robotStartPos = [0.,0.,0.])
    robot1.add_box(position=[0.15, -0.05, 0.01], friction=0.5)
    robot1.add_box(position=[0.15, -0.05, 0.07], friction=0.5)
    robot1.add_box(position=[0.15, -0.05, 0.13], friction=0.5)
    # we put the 2nd robot 0.3m away
    robot2 = NYUFingerSimulator(robotStartPos = [0.3,0.,0.])
    # we reset the simulation to the initial position we want to move
    robot1.reset_state(np.array([0.0,0.0,0.5]))
    robot2.reset_state(np.array([0.0,0.0,-0.5]))

# we reset the simulation
if use_real_robot:
    # we wait
    for i in range(7500):
        robot1.send_joint_torque(np.zeros([3,1]))
        robot2.send_joint_torque(np.zeros([3,1]))
        robot1.step()

# we simulate for 10 seconds
run_time = 13.
dt = 0.001
num_steps = int(run_time/dt)

# the PD gains
P = np.array([1.5, 1.5, 1.5])
D = np.array([0.05, 0.05, 0.05])


## we allocate a few vectors to collect data while we do the simulation
# we keep track of time
time = np.zeros([num_steps])
# we will store the sensor values (angular position and velocities)
measured_positions_f1 = np.zeros([num_steps,3])
measured_velocities_f1 = np.zeros_like(measured_positions_f1)
measured_positions_f2 = np.zeros_like(measured_positions_f1)
measured_velocities_f2 = np.zeros_like(measured_positions_f1)
# we will store the end effector position (desired and measured)
measured_finger_position_f1 = np.zeros([num_steps,3])
desired_finger_position_f1 = np.zeros([num_steps,3])
measured_finger_position_f2 = np.zeros([num_steps,3])
desired_finger_position_f2 = np.zeros([num_steps,3])

time_to_goal = 1.5
block_number = 0
t = 0


for i in range(num_steps):
    # get the current time and save it
    time[i] = dt * i
    
    # we get the position and velocities of the joints
    q1, dq1 = robot1.get_state()
    q2, dq2 = robot2.get_state()
    
    # controller: TODO HERE IMPLEMENT YOUR CONTROLLER

    joint_torques1 = np.zeros([3,1])
    joint_torques2 = np.zeros([3,1])
    
    pose1 = forward_kinematics(q1)
    measured_finger_position_f1[i,:] = pose1[0:3,3]
    print(measured_finger_position_f1[i,:])
    
    if(time[i] == 0):
        q_mog, pos_mog, init_time_mog, time_to_mog = \
        (measured_finger_position_f1[i,:], pos_1, 0, time_to_goal)
        
    pos_des, vel_des = second_order_trajectory(q_mog, \
                        pos_mog, init_time_mog, time_to_mog, time[i])

    
    # we send them to the robot and do one simulation step
    J1 = getBodyJacobianOrientedLikeSpatialFrame(q1);
    
    K = np.array([[10, 0, 0],
                  [0, 10, 0],
                  [0, 0, 10]])
    
    D = np.array([[.5, 0, 0],
                  [0, .5, 0],
                  [0, 0, .5]])
    
    desired_finger_position_f1[i, :] = pos_des
    desired_velocities_f1= vel_des
    
    joint_torques1 = J1.T @ (K @ (desired_finger_position_f1[i, :] - measured_finger_position_f1[i,:]) + \
                  D @ (desired_velocities_f1 - (J1 @ dq1)))
        
    # we send them to the robot and do one simulation step
    robot1.send_joint_torque(joint_torques1)
    #robot2.send_joint_torque(joint_torques2)
    robot1.step()

[ 0.37670809 -0.30041321  0.014     ]
[ 0.37670412 -0.30041605  0.01400457]
[ 0.37669629 -0.30042169  0.01401368]
[ 0.37668467 -0.30043006  0.01402727]
[ 0.37666936 -0.30044111  0.01404532]
[ 0.37665044 -0.3004548   0.01406776]
[ 0.37662802 -0.30047106  0.01409458]
[ 0.37660217 -0.30048983  0.01412571]
[ 0.37657299 -0.30051107  0.01416112]
[ 0.37654056 -0.30053472  0.01420076]
[ 0.37650497 -0.30056071  0.01424458]
[ 0.37646632 -0.30058899  0.01429255]
[ 0.37642468 -0.3006195   0.01434461]
[ 0.37638014 -0.30065219  0.01440071]
[ 0.37633279 -0.30068699  0.01446082]
[ 0.37628272 -0.30072385  0.01452489]
[ 0.37623    -0.3007627   0.01459286]
[ 0.37617473 -0.30080349  0.01466468]
[ 0.37611699 -0.30084615  0.01474032]
[ 0.37605686 -0.30089064  0.01481971]
[ 0.37599442 -0.30093688  0.01490281]
[ 0.37592976 -0.30098482  0.01498958]
[ 0.37586295 -0.30103441  0.01507995]
[ 0.37579409 -0.30108557  0.01517388]
[ 0.37572324 -0.30113826  0.01527131]
[ 0.37565048 -0.30119241  0.0153722 ]
[ 0.37557591

[ 0.37899889 -0.30509172  0.03783726]
[ 0.37907876 -0.30506012  0.03776812]
[ 0.37915829 -0.30502821  0.03769866]
[ 0.37923747 -0.30499599  0.03762892]
[ 0.37931631 -0.30496346  0.0375589 ]
[ 0.37939481 -0.30493061  0.03748862]
[ 0.37947295 -0.30489744  0.03741812]
[ 0.37955074 -0.30486394  0.03734739]
[ 0.37962818 -0.30483011  0.03727648]
[ 0.37970527 -0.30479594  0.03720539]
[ 0.37978199 -0.30476144  0.03713414]
[ 0.37985836 -0.30472658  0.03706275]
[ 0.37993437 -0.30469138  0.03699125]
[ 0.38001002 -0.30465582  0.03691964]
[ 0.38008531 -0.30461991  0.03684796]
[ 0.38016023 -0.30458363  0.03677621]
[ 0.38023479 -0.30454698  0.03670442]
[ 0.38030899 -0.30450996  0.0366326 ]
[ 0.38038282 -0.30447256  0.03656076]
[ 0.38045629 -0.30443479  0.03648894]
[ 0.38052939 -0.30439662  0.03641715]
[ 0.38060213 -0.30435806  0.03634539]
[ 0.3806745  -0.30431911  0.03627369]
[ 0.3807465  -0.30427975  0.03620208]
[ 0.38081814 -0.30424     0.03613055]
[ 0.38088941 -0.30419983  0.03605913]
[ 0.38096032

[ 0.39316243 -0.28067271  0.03254418]
[ 0.39322755 -0.28055963  0.0325568 ]
[ 0.39329312 -0.28044682  0.03256926]
[ 0.39335913 -0.28033427  0.03258158]
[ 0.3934256  -0.28022198  0.03259373]
[ 0.39349251 -0.28010997  0.03260574]
[ 0.39355989 -0.27999822  0.03261758]
[ 0.39362772 -0.27988675  0.03262927]
[ 0.393696   -0.27977554  0.0326408 ]
[ 0.39376475 -0.2796646   0.03265216]
[ 0.39383396 -0.27955394  0.03266336]
[ 0.39390364 -0.27944355  0.0326744 ]
[ 0.39397377 -0.27933343  0.03268527]
[ 0.39404438 -0.27922359  0.03269598]
[ 0.39411545 -0.27911402  0.03270652]
[ 0.39418699 -0.27900472  0.03271689]
[ 0.39425901 -0.2788957   0.03272709]
[ 0.39433149 -0.27878695  0.03273712]
[ 0.39440444 -0.27867847  0.03274698]
[ 0.39447787 -0.27857026  0.03275667]
[ 0.39455177 -0.27846233  0.03276618]
[ 0.39462615 -0.27835467  0.03277553]
[ 0.394701   -0.27824729  0.0327847 ]
[ 0.39477633 -0.27814017  0.03279369]
[ 0.39485214 -0.27803332  0.03280251]
[ 0.39492842 -0.27792675  0.03281116]
[ 0.39500517

[ 0.41466685 -0.25771914  0.032342  ]
[ 0.41466652 -0.25766644  0.03233817]
[ 0.41466619 -0.25761274  0.03233426]
[ 0.41466585 -0.25755802  0.03233029]
[ 0.41466551 -0.25750228  0.03232624]
[ 0.41466516 -0.25744554  0.03232212]
[ 0.41466481 -0.25738778  0.03231793]
[ 0.41466446 -0.25732902  0.03231366]
[ 0.4146641  -0.25726924  0.03230932]
[ 0.41466374 -0.25720845  0.03230491]
[ 0.41466337 -0.25714666  0.03230043]
[ 0.414663   -0.25708386  0.03229587]
[ 0.41466263 -0.25702005  0.03229125]
[ 0.41466225 -0.25695524  0.03228655]
[ 0.41466187 -0.25688942  0.03228178]
[ 0.41466149 -0.2568226   0.03227694]
[ 0.4146611  -0.25675479  0.03227202]
[ 0.41466069 -0.256686    0.03226704]
[ 0.4146603  -0.25661619  0.03226199]
[ 0.4146599  -0.25654539  0.03225686]
[ 0.4146595  -0.2564736   0.03225166]
[ 0.4146591  -0.25640081  0.03224639]
[ 0.4146587  -0.25632705  0.03224106]
[ 0.41465829 -0.25625229  0.03223565]
[ 0.41465789 -0.25617656  0.03223017]
[ 0.41465748 -0.25609985  0.03222462]
[ 0.41465707

[ 0.41473228 -0.22842449  0.03022083]
[ 0.41472297 -0.22837017  0.03021796]
[ 0.41471417 -0.22831706  0.03021584]
[ 0.41470592 -0.22826517  0.03021431]
[ 0.41469821 -0.22821453  0.03021321]
[ 0.41469104 -0.22816517  0.0302124 ]
[ 0.41468441 -0.2281171   0.03021179]
[ 0.41467833 -0.22807033  0.0302113 ]
[ 0.4146728  -0.22802485  0.03021089]
[ 0.41466781 -0.22798065  0.03021051]
[ 0.4146634  -0.2279377   0.03021013]
[ 0.41466571 -0.22788556  0.03021055]
[ 0.41467462 -0.22782441  0.03021174]
[ 0.41469003 -0.22775445  0.03021368]
[ 0.41471184 -0.22767586  0.03021634]
[ 0.41473994 -0.22758884  0.03021971]
[ 0.41474586 -0.22753353  0.03022165]
[ 0.41474971 -0.227482    0.03022186]
[ 0.41475287 -0.22743226  0.03022057]
[ 0.41475537 -0.22738413  0.03021822]
[ 0.4147572  -0.2273374   0.03021533]
[ 0.41475852 -0.22729188  0.03021194]
[ 0.41475937 -0.22724741  0.03020825]
[ 0.41475981 -0.22720385  0.03020447]
[ 0.41476002 -0.22716092  0.03020063]
[ 0.41476013 -0.22711844  0.03019674]
[ 0.41476119

[ 0.42847204 -0.20427742  0.0285658 ]
[ 0.42854696 -0.20418284  0.02855882]
[ 0.42862167 -0.20408871  0.02855186]
[ 0.42869618 -0.20399502  0.02854498]
[ 0.42877049 -0.20390166  0.02853835]
[ 0.42884457 -0.20380871  0.02853194]
[ 0.42891838 -0.20371624  0.02852575]
[ 0.42899196 -0.2036242   0.02851972]
[ 0.42906531 -0.2035326   0.0285138 ]
[ 0.42913842 -0.20344146  0.02850795]
[ 0.42921129 -0.20335081  0.02850215]
[ 0.42928392 -0.20326065  0.02849635]
[ 0.4293563  -0.20317099  0.02849057]
[ 0.42942843 -0.20308185  0.02848477]
[ 0.4295003  -0.20299323  0.02847898]
[ 0.4295719  -0.20290512  0.02847317]
[ 0.42964326 -0.20281752  0.02846736]
[ 0.42971435 -0.20273043  0.02846155]
[ 0.42978517 -0.20264387  0.02845574]
[ 0.42985571 -0.20255783  0.02844994]
[ 0.42992597 -0.20247233  0.02844414]
[ 0.42999594 -0.20238735  0.02843836]
[ 0.43006563 -0.2023029   0.0284326 ]
[ 0.43013503 -0.20221899  0.02842685]
[ 0.43020414 -0.20213561  0.02842113]
[ 0.43027295 -0.20205276  0.02841542]
[ 0.43034146

[ 0.44524181 -0.18684257  0.02863641]
[ 0.44529358 -0.18684828  0.02867653]
[ 0.44534474 -0.18685535  0.02871707]
[ 0.44539527 -0.18686379  0.02875805]
[ 0.44544518 -0.18687359  0.02879944]
[ 0.44549444 -0.18688476  0.02884123]
[ 0.44554306 -0.18689729  0.02888343]
[ 0.44559103 -0.18691118  0.02892603]
[ 0.44563833 -0.18692642  0.028969  ]
[ 0.44568496 -0.18694302  0.02901236]
[ 0.44573091 -0.18696098  0.02905609]
[ 0.44577618 -0.18698028  0.02910018]
[ 0.44582075 -0.18700092  0.02914462]
[ 0.44586463 -0.18702291  0.02918941]
[ 0.44590779 -0.18704623  0.02923454]
[ 0.44595025 -0.18707089  0.02928   ]
[ 0.44599198 -0.18709687  0.02932578]
[ 0.44603299 -0.18712418  0.02937188]
[ 0.44607326 -0.1871528   0.02941828]
[ 0.44611279 -0.18718273  0.02946499]
[ 0.44615158 -0.18721397  0.02951198]
[ 0.44618962 -0.18724651  0.02955926]
[ 0.44622689 -0.18728034  0.02960682]
[ 0.44626341 -0.18731545  0.02965464]
[ 0.44629915 -0.18735184  0.02970272]
[ 0.44633412 -0.18738951  0.02975106]
[ 0.44636831

[ 0.43334656 -0.21558745  0.03468182]
[ 0.43330909 -0.21559519  0.03465903]
[ 0.43327192 -0.21560298  0.03463609]
[ 0.43323504 -0.21561082  0.03461301]
[ 0.43319846 -0.21561871  0.0345898 ]
[ 0.43316219 -0.21562663  0.03456649]
[ 0.43312622 -0.21563459  0.03454306]
[ 0.43309056 -0.21564259  0.03451955]
[ 0.43305521 -0.21565061  0.03449596]
[ 0.43302017 -0.21565865  0.0344723 ]
[ 0.43298544 -0.21566672  0.03444858]
[ 0.43295102 -0.2156748   0.03442482]
[ 0.43291691 -0.2156829   0.03440102]
[ 0.43288313 -0.215691    0.0343772 ]
[ 0.43284966 -0.21569911  0.03435336]
[ 0.43281651 -0.21570722  0.03432953]
[ 0.43278369 -0.21571533  0.0343057 ]
[ 0.43275118 -0.21572343  0.0342819 ]
[ 0.432719   -0.21573152  0.03425812]
[ 0.43268715 -0.21573959  0.03423439]
[ 0.43265562 -0.21574765  0.0342107 ]
[ 0.43262442 -0.21575568  0.03418708]
[ 0.43259354 -0.21576369  0.03416354]
[ 0.432563   -0.21577167  0.03414007]
[ 0.43253278 -0.21577962  0.03411669]
[ 0.4325029  -0.21578754  0.03409342]
[ 0.43247335

[ 0.43124483 -0.21614034  0.0330581 ]
[ 0.43124472 -0.21614037  0.03305803]
[ 0.4312446  -0.2161404   0.03305795]
[ 0.43124449 -0.21614044  0.03305787]
[ 0.43124438 -0.21614047  0.0330578 ]
[ 0.43124426 -0.2161405   0.03305772]
[ 0.43124415 -0.21614053  0.03305764]
[ 0.43124403 -0.21614056  0.03305756]
[ 0.43124391 -0.21614059  0.03305748]
[ 0.4312438  -0.21614063  0.03305741]
[ 0.43124368 -0.21614066  0.03305733]
[ 0.43124356 -0.21614069  0.03305725]
[ 0.43124344 -0.21614072  0.03305717]
[ 0.43124332 -0.21614075  0.03305709]
[ 0.4312432  -0.21614079  0.03305701]
[ 0.43124308 -0.21614082  0.03305693]
[ 0.43124296 -0.21614085  0.03305685]
[ 0.43124284 -0.21614089  0.03305677]
[ 0.43124272 -0.21614092  0.03305669]
[ 0.43124259 -0.21614095  0.03305661]
[ 0.43124247 -0.21614098  0.03305652]
[ 0.43124235 -0.21614102  0.03305644]
[ 0.43124222 -0.21614105  0.03305636]
[ 0.43124209 -0.21614108  0.03305628]
[ 0.43124197 -0.21614112  0.03305619]
[ 0.43124184 -0.21614115  0.03305611]
[ 0.43124171

[ 0.42076554 -0.2165365   0.03187722]
[ 0.4205831  -0.21654457  0.0318773 ]
[ 0.42039801 -0.21655312  0.03187738]
[ 0.42021024 -0.21656215  0.03187748]
[ 0.42001975 -0.21657169  0.03187758]
[ 0.41982652 -0.21658176  0.03187769]
[ 0.4196305  -0.21659238  0.03187782]
[ 0.41943167 -0.21660355  0.03187795]
[ 0.41922998 -0.21661532  0.03187809]
[ 0.41902541 -0.21662768  0.03187824]
[ 0.41881792 -0.21664068  0.03187841]
[ 0.41860746 -0.21665432  0.03187858]
[ 0.41839401 -0.21666864  0.03187876]
[ 0.41817752 -0.21668365  0.03187896]
[ 0.41795797 -0.21669938  0.03187917]
[ 0.4177353  -0.21671585  0.03187939]
[ 0.41750948 -0.2167331   0.03187962]
[ 0.41728048 -0.21675114  0.03187986]
[ 0.41704825 -0.21677001  0.03188012]
[ 0.41681275 -0.21678972  0.03188039]
[ 0.41657395 -0.21681032  0.03188068]
[ 0.41633179 -0.21683184  0.03188097]
[ 0.41608624 -0.21685429  0.03188129]
[ 0.41583725 -0.21687771  0.03188161]
[ 0.41558478 -0.21690215  0.03188196]
[ 0.41532947 -0.21691993  0.03188222]
[ 0.41507111

[ 0.28318475 -0.31238559  0.03436137]
[ 0.28381875 -0.31266641  0.03429535]
[ 0.28445257 -0.31294769  0.0342291 ]
[ 0.28508516 -0.31322858  0.03416273]
[ 0.28571543 -0.31350821  0.03409637]
[ 0.28634231 -0.31378577  0.03403012]
[ 0.28696472 -0.31406045  0.0339641 ]
[ 0.28758156 -0.31433148  0.03389842]
[ 0.28819175 -0.31459813  0.03383318]
[ 0.2887942  -0.31485968  0.03376849]
[ 0.28938782 -0.31511548  0.03370445]
[ 0.28997152 -0.3153649   0.03364116]
[ 0.29054423 -0.31560734  0.03357871]
[ 0.29110486 -0.31584227  0.0335172 ]
[ 0.29165235 -0.31606919  0.03345671]
[ 0.29218564 -0.31628764  0.03339733]
[ 0.29270369 -0.31649723  0.03333912]
[ 0.29320546 -0.31669759  0.03328216]
[ 0.29368994 -0.31688843  0.03322652]
[ 0.29415613 -0.31706949  0.03317226]
[ 0.29460305 -0.31724057  0.03311943]
[ 0.29502976 -0.3174015   0.03306809]
[ 0.29543532 -0.3175522   0.03301827]
[ 0.29581884 -0.31769259  0.03297002]
[ 0.29617944 -0.31782268  0.03292336]
[ 0.29651629 -0.3179425   0.03287834]
[ 0.29682857

[ 0.24324772 -0.31354432  0.03139063]
[ 0.24342549 -0.31357329  0.03141036]
[ 0.24359664 -0.31360091  0.03143069]
[ 0.24376105 -0.31362715  0.03145158]
[ 0.24391858 -0.313652    0.03147302]
[ 0.24406909 -0.31367545  0.03149499]
[ 0.24421248 -0.31369748  0.03151747]
[ 0.24434864 -0.3137181   0.03154044]
[ 0.24447747 -0.3137373   0.03156388]
[ 0.24459891 -0.31375507  0.03158776]
[ 0.24471288 -0.31377142  0.03161207]
[ 0.24481931 -0.31378633  0.03163679]
[ 0.24491817 -0.31379983  0.03166188]
[ 0.2450094  -0.3138119   0.03168734]
[ 0.24509299 -0.31382256  0.03171313]
[ 0.24516892 -0.31383181  0.03173924]
[ 0.24523717 -0.31383967  0.03176563]
[ 0.24529775 -0.31384614  0.0317923 ]
[ 0.24535067 -0.31385123  0.03181922]
[ 0.24539595 -0.31385496  0.03184636]
[ 0.24543362 -0.31385734  0.03187371]
[ 0.24546371 -0.31385839  0.03190123]
[ 0.24548627 -0.31385812  0.03192891]
[ 0.24550136 -0.31385656  0.03195673]
[ 0.24550904 -0.31385371  0.03198465]
[ 0.24550937 -0.31384962  0.03201267]
[ 0.24550243

[ 0.22140368 -0.30880218  0.03203119]
[ 0.22134195 -0.30878496  0.03205365]
[ 0.22127758 -0.30876714  0.0320756 ]
[ 0.22121058 -0.30874873  0.03209703]
[ 0.22114094 -0.30872973  0.03211792]
[ 0.22106867 -0.30871012  0.03213825]
[ 0.22099378 -0.30868991  0.032158  ]
[ 0.22091627 -0.3086691   0.03217716]
[ 0.22083614 -0.30864769  0.03219571]
[ 0.22075341 -0.30862567  0.03221362]
[ 0.22066809 -0.30860304  0.03223089]
[ 0.22058018 -0.30857981  0.0322475 ]
[ 0.22048971 -0.30855597  0.03226343]
[ 0.22039669 -0.30853153  0.03227867]
[ 0.22030114 -0.30850648  0.03229321]
[ 0.22020307 -0.30848082  0.03230703]
[ 0.22010252 -0.30845457  0.03232013]
[ 0.2199995  -0.30842771  0.03233248]
[ 0.21989405 -0.30840026  0.03234408]
[ 0.21978619 -0.30837222  0.03235491]
[ 0.21967595 -0.30834359  0.03236497]
[ 0.21956339 -0.30831438  0.03237425]
[ 0.21944852 -0.30828459  0.03238274]
[ 0.21933139 -0.30825424  0.03239043]
[ 0.21921205 -0.30822333  0.03239731]
[ 0.21909055 -0.30819186  0.03240338]
[ 0.21896693

[ 0.20309663 -0.3037171   0.03095394]
[ 0.20303871 -0.30370074  0.03093347]
[ 0.20298194 -0.30368472  0.03091315]
[ 0.20292634 -0.30366903  0.03089299]
[ 0.20287191 -0.30365368  0.03087302]
[ 0.20281867 -0.30363868  0.03085326]
[ 0.20276663 -0.30362401  0.03083373]
[ 0.20271578 -0.30360969  0.03081445]
[ 0.20266614 -0.30359571  0.03079543]
[ 0.20261771 -0.30358208  0.03077671]
[ 0.2025705  -0.30356879  0.03075829]
[ 0.20252451 -0.30355584  0.03074019]
[ 0.20247975 -0.30354324  0.03072244]
[ 0.20243622 -0.30353098  0.03070506]
[ 0.20239391 -0.30351907  0.03068805]
[ 0.20235283 -0.3035075   0.03067144]
[ 0.20231298 -0.30349627  0.03065524]
[ 0.20227436 -0.30348538  0.03063947]
[ 0.20223696 -0.30347483  0.03062414]
[ 0.20220079 -0.30346462  0.03060927]
[ 0.20216582 -0.30345474  0.03059488]
[ 0.20213207 -0.3034452   0.03058097]
[ 0.20209953 -0.30343598  0.03056756]
[ 0.20206817 -0.30342708  0.03055466]
[ 0.202038   -0.30341851  0.03054229]
[ 0.20200901 -0.30341026  0.03053045]
[ 0.20198117

[ 0.19521474 -0.30110753  0.03075089]
[ 0.19518587 -0.30109725  0.03075359]
[ 0.19515658 -0.30108685  0.03075594]
[ 0.19512686 -0.30107634  0.03075795]
[ 0.19509672 -0.30106571  0.0307596 ]
[ 0.19506618 -0.30105498  0.0307609 ]
[ 0.19503524 -0.30104414  0.03076184]
[ 0.19500391 -0.3010332   0.03076243]
[ 0.19497221 -0.30102216  0.03076266]
[ 0.19494015 -0.30101104  0.03076252]
[ 0.19490774 -0.30099982  0.03076203]
[ 0.19487499 -0.30098852  0.03076118]
[ 0.19484193 -0.30097714  0.03075997]
[ 0.19480855 -0.30096569  0.0307584 ]
[ 0.19477488 -0.30095416  0.03075648]
[ 0.19474094 -0.30094258  0.03075422]
[ 0.19470674 -0.30093093  0.0307516 ]
[ 0.19467229 -0.30091923  0.03074864]
[ 0.19463762 -0.30090748  0.03074534]
[ 0.19460274 -0.30089568  0.03074171]
[ 0.19456766 -0.30088385  0.03073775]
[ 0.19453241 -0.30087198  0.03073347]
[ 0.194497   -0.30086009  0.03072887]
[ 0.19446145 -0.30084817  0.03072397]
[ 0.19442578 -0.30083624  0.03071876]
[ 0.19439001 -0.30082429  0.03071327]
[ 0.19435415

[ 0.18880063 -0.29885385  0.03024051]
[ 0.1887855  -0.29884796  0.03024306]
[ 0.18877028 -0.29884204  0.03024556]
[ 0.18875498 -0.2988361   0.030248  ]
[ 0.18873957 -0.29883013  0.03025036]
[ 0.18872407 -0.29882412  0.03025264]
[ 0.18870846 -0.29881809  0.03025484]
[ 0.18869274 -0.29881202  0.03025695]
[ 0.18867691 -0.29880592  0.03025896]
[ 0.18866096 -0.29879979  0.03026088]
[ 0.18864488 -0.29879362  0.03026268]
[ 0.18862869 -0.29878742  0.03026438]
[ 0.18861236 -0.29878117  0.03026596]
[ 0.1885959  -0.2987749   0.03026742]
[ 0.18857931 -0.29876858  0.03026876]
[ 0.18856258 -0.29876222  0.03026996]
[ 0.18854572 -0.29875583  0.03027104]
[ 0.18852872 -0.2987494   0.03027198]
[ 0.18851158 -0.29874293  0.03027279]
[ 0.1884943  -0.29873642  0.03027345]
[ 0.18847687 -0.29872987  0.03027397]
[ 0.18845931 -0.29872329  0.03027435]
[ 0.18844161 -0.29871666  0.03027457]
[ 0.18842377 -0.29871     0.03027465]
[ 0.18840579 -0.2987033   0.03027459]
[ 0.18838767 -0.29869656  0.03027437]
[ 0.18836942

[ 0.18439353 -0.2972029   0.02999961]
[ 0.18438106 -0.29719806  0.0299995 ]
[ 0.18436854 -0.29719321  0.02999934]
[ 0.18435598 -0.29718835  0.02999912]
[ 0.18434337 -0.29718347  0.02999885]
[ 0.18433071 -0.29717858  0.02999853]
[ 0.18431801 -0.29717368  0.02999816]
[ 0.18430525 -0.29716876  0.02999772]
[ 0.18429244 -0.29716383  0.02999723]
[ 0.18427958 -0.29715888  0.02999669]
[ 0.18426667 -0.29715391  0.02999609]
[ 0.1842537  -0.29714894  0.02999543]
[ 0.18424069 -0.29714394  0.02999472]
[ 0.18422763 -0.29713894  0.02999396]
[ 0.18421451 -0.29713392  0.02999313]
[ 0.18420135 -0.29712888  0.02999226]
[ 0.18418814 -0.29712383  0.02999133]
[ 0.18417489 -0.29711877  0.02999035]
[ 0.18416159 -0.29711369  0.02998931]
[ 0.18414824 -0.2971086   0.02998823]
[ 0.18413486 -0.2971035   0.02998709]
[ 0.18412143 -0.29709839  0.02998591]
[ 0.18410796 -0.29709327  0.02998469]
[ 0.18409445 -0.29708813  0.02998341]
[ 0.18408091 -0.29708299  0.0299821 ]
[ 0.18406734 -0.29707784  0.02998074]
[ 0.18405373

[ 0.18117842 -0.29595395  0.02979397]
[ 0.18116825 -0.29594996  0.02979303]
[ 0.18115809 -0.29594597  0.02979209]
[ 0.18114794 -0.295942    0.02979116]
[ 0.18113781 -0.29593803  0.02979024]
[ 0.18112771 -0.29593406  0.02978932]
[ 0.18111762 -0.29593011  0.0297884 ]
[ 0.18110755 -0.29592616  0.02978749]
[ 0.18109751 -0.29592222  0.0297866 ]
[ 0.1810875  -0.29591828  0.02978571]
[ 0.18107751 -0.29591436  0.02978483]
[ 0.18106754 -0.29591045  0.02978396]
[ 0.18105761 -0.29590654  0.02978311]
[ 0.1810477  -0.29590265  0.02978227]
[ 0.18103782 -0.29589876  0.02978144]
[ 0.18102798 -0.29589489  0.02978062]
[ 0.18101816 -0.29589103  0.02977983]
[ 0.18100838 -0.29588718  0.02977904]
[ 0.18099863 -0.29588334  0.02977827]
[ 0.18098892 -0.29587951  0.02977752]
[ 0.18097924 -0.29587569  0.02977679]
[ 0.1809696  -0.29587188  0.02977607]
[ 0.18095998 -0.29586809  0.02977537]
[ 0.18095041 -0.29586431  0.02977469]
[ 0.18094087 -0.29586054  0.02977402]
[ 0.18093137 -0.29585678  0.02977337]
[ 0.1809219 

[ 0.17878928 -0.2949987   0.0296488 ]
[ 0.17878212 -0.2949958   0.02964844]
[ 0.17877495 -0.29499289  0.02964807]
[ 0.17876779 -0.29498999  0.02964769]
[ 0.17876062 -0.29498708  0.0296473 ]
[ 0.17875345 -0.29498418  0.02964691]
[ 0.17874627 -0.29498127  0.02964651]
[ 0.17873909 -0.29497836  0.02964611]
[ 0.17873191 -0.29497545  0.02964569]
[ 0.17872473 -0.29497254  0.02964527]
[ 0.17871754 -0.29496963  0.02964484]
[ 0.17871035 -0.29496672  0.02964441]
[ 0.17870316 -0.29496381  0.02964397]
[ 0.17869597 -0.2949609   0.02964352]
[ 0.17868877 -0.29495799  0.02964306]
[ 0.17868157 -0.29495507  0.02964259]
[ 0.17867437 -0.29495216  0.02964212]
[ 0.17866717 -0.29494925  0.02964164]
[ 0.17865997 -0.29494634  0.02964116]
[ 0.17865277 -0.29494342  0.02964066]
[ 0.17864556 -0.29494051  0.02964017]
[ 0.17863836 -0.2949376   0.02963966]
[ 0.17863115 -0.29493469  0.02963915]
[ 0.17862395 -0.29493178  0.02963864]
[ 0.17861675 -0.29492887  0.02963811]
[ 0.17860955 -0.29492596  0.02963759]
[ 0.17860236

[ 0.17703061 -0.29428154  0.0295371 ]
[ 0.17702509 -0.29427927  0.02953679]
[ 0.17701958 -0.294277    0.02953648]
[ 0.17701408 -0.29427473  0.02953618]
[ 0.17700857 -0.29427246  0.02953587]
[ 0.17700308 -0.2942702   0.02953557]
[ 0.17699758 -0.29426793  0.02953526]
[ 0.17699209 -0.29426567  0.02953495]
[ 0.1769866  -0.29426341  0.02953464]
[ 0.17698112 -0.29426115  0.02953433]
[ 0.17697564 -0.29425889  0.02953402]
[ 0.17697016 -0.29425663  0.02953371]
[ 0.17696468 -0.29425437  0.02953339]
[ 0.1769592  -0.29425211  0.02953308]
[ 0.17695373 -0.29424986  0.02953276]
[ 0.17694826 -0.2942476   0.02953244]
[ 0.17694279 -0.29424535  0.02953211]
[ 0.17693732 -0.2942431   0.02953179]
[ 0.17693186 -0.29424084  0.02953146]
[ 0.17692639 -0.29423859  0.02953113]
[ 0.17692093 -0.29423634  0.02953079]
[ 0.17691547 -0.29423409  0.02953046]
[ 0.17691001 -0.29423184  0.02953012]
[ 0.17690455 -0.29422959  0.02952978]
[ 0.17689909 -0.29422735  0.02952943]
[ 0.17689364 -0.2942251   0.02952908]
[ 0.17688818

[ 0.17567303 -0.29371951  0.0294505 ]
[ 0.17566868 -0.2937177   0.02945023]
[ 0.17566434 -0.29371588  0.02944996]
[ 0.17566    -0.29371408  0.02944969]
[ 0.17565566 -0.29371227  0.02944942]
[ 0.17565133 -0.29371046  0.02944915]
[ 0.175647   -0.29370865  0.02944888]
[ 0.17564266 -0.29370685  0.02944861]
[ 0.17563834 -0.29370504  0.02944833]
[ 0.17563401 -0.29370324  0.02944806]
[ 0.17562969 -0.29370144  0.02944779]
[ 0.17562537 -0.29369964  0.02944751]
[ 0.17562105 -0.29369783  0.02944723]
[ 0.17561673 -0.29369604  0.02944695]
[ 0.17561242 -0.29369424  0.02944668]
[ 0.1756081  -0.29369244  0.0294464 ]
[ 0.17560379 -0.29369064  0.02944612]
[ 0.17559949 -0.29368885  0.02944583]
[ 0.17559518 -0.29368705  0.02944555]
[ 0.17559088 -0.29368526  0.02944527]
[ 0.17558658 -0.29368347  0.02944498]
[ 0.17558228 -0.29368168  0.0294447 ]
[ 0.17557799 -0.29367989  0.02944441]
[ 0.1755737  -0.2936781   0.02944413]
[ 0.17556941 -0.29367631  0.02944384]
[ 0.17556512 -0.29367452  0.02944356]
[ 0.17556084

[ 0.17459233 -0.29326692  0.02938024]
[ 0.17458887 -0.29326547  0.02938   ]
[ 0.17458541 -0.29326401  0.02937977]
[ 0.17458196 -0.29326256  0.02937954]
[ 0.17457851 -0.29326111  0.02937931]
[ 0.17457506 -0.29325965  0.02937908]
[ 0.17457161 -0.2932582   0.02937885]
[ 0.17456817 -0.29325676  0.02937862]
[ 0.17456473 -0.29325531  0.0293784 ]
[ 0.1745613  -0.29325386  0.02937817]
[ 0.17455787 -0.29325242  0.02937794]
[ 0.17455444 -0.29325097  0.02937771]
[ 0.17455101 -0.29324953  0.02937749]
[ 0.17454759 -0.29324809  0.02937726]
[ 0.17454417 -0.29324665  0.02937704]
[ 0.17454076 -0.29324521  0.02937681]
[ 0.17453734 -0.29324378  0.02937659]
[ 0.17453393 -0.29324234  0.02937636]
[ 0.17453053 -0.29324091  0.02937614]
[ 0.17452713 -0.29323947  0.02937592]
[ 0.17452373 -0.29323804  0.0293757 ]
[ 0.17452033 -0.29323661  0.02937548]
[ 0.17451694 -0.29323518  0.02937526]
[ 0.17451355 -0.29323375  0.02937504]
[ 0.17451016 -0.29323233  0.02937482]
[ 0.17450678 -0.2932309   0.0293746 ]
[ 0.1745034 